wordpress:
  build: .
  links: 
   - db
  ports:
   - "80:80"
  environment:
    DATA_DB_NAME: wordpress
    DATA_DB_USER: admin
    DATA_DB_PASS: "**ChangeMe**"
    DB_HOST: "**LinkMe**"
    DB_PORT: "**LinkMe**"
db:
  image: tutum/mysql:5.5
  environment:
    MYSQL_PASS: "**ChangeMe**"
